In [195]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [196]:
df_550 = pd.read_csv('Sample size of even 550.csv')
df_942 = pd.read_csv('Sample size of even 942.csv')
df_1636 = pd.read_csv('Sample size of even 1636.csv')
df_1951 = pd.read_csv('Sample size of even 1951.csv')

In [197]:
#we're combining the csvs and removing the nan data in the result column
combined_df = pd.concat([df_550,df_942,df_1636,df_1951],ignore_index=True)

In [198]:
df = combined_df[combined_df['Result'].notna()]

In [199]:
df.shape

(784, 23)

In [200]:
df.drop(df.columns[0], axis=1,inplace=True)
df.drop(['Ethnicity','Gender'],axis=1,inplace=True)

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\2636254271.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(df.columns[0], axis=1,inplace=True)
C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\2636254271.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['Ethnicity','Gender'],axis=1,inplace=True)

In [201]:
df.head()

,Age,BMI,Diet Servings,Number of Servings,Mod Activity,Mod_Hours,Vig Activity,Vig Hours,Colonoscopy,Polyp,Meds_one,Meds_Two,Family History,Family Numbers,Cigarettes,Smoking_Age,Currently Smoking,Quit_Age,No of Cigarettes,Result
0,72,29.24,None,NaN,1.0,Up to 1 hour/week,NaN,3 - 4 hours/week,No,NaN,Yes,Yes,No,NaN,Yes,19.0,Yes,NaN,1 to 10 cigarettes a day,2.3%
1,58,29.75,3-4 servings/week,More than 5 cups,5.0,2 - 3 hours/week,NaN,3 - 4 hours/week,No,NaN,No,No,Yes,1,Yes,15.0,No,51.0,More than 20 cigarettes a day,7.4%
2,79,24.32,None,NaN,12.0,More than 4 hours/week,NaN,Between 1 - 2 hours/week,No,NaN,Yes,Yes,No,NaN,No,NaN,NaN,NaN,NaN,1.5%
3,66,31.41,More than 10 servings/week,3 cups - 5 cups,12.0,2 - 3 hours/week,NaN,3 - 4 hours/week,No,NaN,Yes,Yes,No,NaN,Yes,2.0,Yes,NaN,More than 20 cigarettes a day,3.6%
4,61,29.41,1-2 servings/week,3 cups - 5 cups,3.0,2 - 3 hours/week,NaN,2 - 3 hours/week,Yes,No,Yes,Yes,No,NaN,Yes,30.0,Yes,NaN,More than 20 cigarettes a day,1.6%

In [202]:
#converting the result column from text to float
df['Result'] = df['Result'].str.replace('%', '').astype(float)

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\1793904041.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Result'] = df['Result'].str.replace('%', '').astype(float)

In [203]:
df.describe()

,Age,BMI,Mod Activity,Vig Activity,Smoking_Age,Quit_Age,Result
count,784.000000,784.000000,784.000000,57.0,355.000000,170.000000,784.000000
mean,61.048469,29.170080,6.149235,0.0,32.123944,46.729412,4.283673
std,10.145440,4.809137,3.725501,0.0,17.576351,14.338584,2.651309
min,45.000000,16.802000,0.000000,0.0,1.000000,14.000000,0.500000
25%,53.000000,25.948000,3.000000,0.0,18.000000,38.000000,2.400000
50%,60.000000,28.780000,6.000000,0.0,31.000000,46.000000,3.700000
75%,68.000000,32.417750,9.000000,0.0,46.000000,57.000000,5.500000
max,84.000000,46.740000,12.000000,0.0,82.000000,82.000000,16.700000

In [204]:
#combining the smoking age and quit age into one column and remove Smoking Age and Quit Age
def calculate_years_smoking(row):
    
    if pd.isna(row['Quit_Age']):
        return row['Smoking_Age']
    else:
        return row['Quit_Age'] - row['Smoking_Age']

df['Years Smoking'] = df.apply(calculate_years_smoking, axis=1)

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\1869722956.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Years Smoking'] = df.apply(calculate_years_smoking, axis=1)

In [205]:
df.drop(['Smoking_Age','Quit_Age','Cigarettes'],axis=1,inplace=True)

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\3529747250.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['Smoking_Age','Quit_Age','Cigarettes'],axis=1,inplace=True)

In [206]:
df['Years Smoking']= df['Years Smoking'].fillna(0)

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\228404509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Years Smoking']= df['Years Smoking'].fillna(0)

In [207]:
df.head()

,Age,BMI,Diet Servings,Number of Servings,Mod Activity,Mod_Hours,Vig Activity,Vig Hours,Colonoscopy,Polyp,Meds_one,Meds_Two,Family History,Family Numbers,Currently Smoking,No of Cigarettes,Result,Years Smoking
0,72,29.24,None,NaN,1.0,Up to 1 hour/week,NaN,3 - 4 hours/week,No,NaN,Yes,Yes,No,NaN,Yes,1 to 10 cigarettes a day,2.3,19.0
1,58,29.75,3-4 servings/week,More than 5 cups,5.0,2 - 3 hours/week,NaN,3 - 4 hours/week,No,NaN,No,No,Yes,1,No,More than 20 cigarettes a day,7.4,36.0
2,79,24.32,None,NaN,12.0,More than 4 hours/week,NaN,Between 1 - 2 hours/week,No,NaN,Yes,Yes,No,NaN,NaN,NaN,1.5,0.0
3,66,31.41,More than 10 servings/week,3 cups - 5 cups,12.0,2 - 3 hours/week,NaN,3 - 4 hours/week,No,NaN,Yes,Yes,No,NaN,Yes,More than 20 cigarettes a day,3.6,2.0
4,61,29.41,1-2 servings/week,3 cups - 5 cups,3.0,2 - 3 hours/week,NaN,2 - 3 hours/week,Yes,No,Yes,Yes,No,NaN,Yes,More than 20 cigarettes a day,1.6,30.0

In [208]:
#label encoding columns: Meds_one, Meds_two, Family History, Family Numbers, Colonoscopy

df['Meds_one'] = df['Meds_one'].map({'Yes':1,'No':0})

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\1201067113.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Meds_one'] = df['Meds_one'].map({'Yes':1,'No':0})

In [209]:
df['Meds_Two'] = df['Meds_Two'].map({'Yes':1,'No':0})

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\1539057088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Meds_Two'] = df['Meds_Two'].map({'Yes':1,'No':0})

In [210]:
df['Colonoscopy'] = df['Colonoscopy'].map({'Yes':1,'No':0})

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\1359558446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Colonoscopy'] = df['Colonoscopy'].map({'Yes':1,'No':0})

In [211]:
df['Family History'] = df['Family History'].map({'Yes':1,'No':0})

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\2734422057.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Family History'] = df['Family History'].map({'Yes':1,'No':0})

In [212]:
df.head()

,Age,BMI,Diet Servings,Number of Servings,Mod Activity,Mod_Hours,Vig Activity,Vig Hours,Colonoscopy,Polyp,Meds_one,Meds_Two,Family History,Family Numbers,Currently Smoking,No of Cigarettes,Result,Years Smoking
0,72,29.24,None,NaN,1.0,Up to 1 hour/week,NaN,3 - 4 hours/week,0,NaN,1,1,0,NaN,Yes,1 to 10 cigarettes a day,2.3,19.0
1,58,29.75,3-4 servings/week,More than 5 cups,5.0,2 - 3 hours/week,NaN,3 - 4 hours/week,0,NaN,0,0,1,1,No,More than 20 cigarettes a day,7.4,36.0
2,79,24.32,None,NaN,12.0,More than 4 hours/week,NaN,Between 1 - 2 hours/week,0,NaN,1,1,0,NaN,NaN,NaN,1.5,0.0
3,66,31.41,More than 10 servings/week,3 cups - 5 cups,12.0,2 - 3 hours/week,NaN,3 - 4 hours/week,0,NaN,1,1,0,NaN,Yes,More than 20 cigarettes a day,3.6,2.0
4,61,29.41,1-2 servings/week,3 cups - 5 cups,3.0,2 - 3 hours/week,NaN,2 - 3 hours/week,1,No,1,1,0,NaN,Yes,More than 20 cigarettes a day,1.6,30.0

In [213]:
df['Family Numbers'] = df['Family Numbers'].map({'NaN':0,'1':1,'2 or more':2})

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\1447367553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Family Numbers'] = df['Family Numbers'].map({'NaN':0,'1':1,'2 or more':2})

In [214]:
df['Family Numbers']= df['Family Numbers'].fillna(0)

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\659259983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Family Numbers']= df['Family Numbers'].fillna(0)

In [215]:
df.head()

,Age,BMI,Diet Servings,Number of Servings,Mod Activity,Mod_Hours,Vig Activity,Vig Hours,Colonoscopy,Polyp,Meds_one,Meds_Two,Family History,Family Numbers,Currently Smoking,No of Cigarettes,Result,Years Smoking
0,72,29.24,None,NaN,1.0,Up to 1 hour/week,NaN,3 - 4 hours/week,0,NaN,1,1,0,0.0,Yes,1 to 10 cigarettes a day,2.3,19.0
1,58,29.75,3-4 servings/week,More than 5 cups,5.0,2 - 3 hours/week,NaN,3 - 4 hours/week,0,NaN,0,0,1,1.0,No,More than 20 cigarettes a day,7.4,36.0
2,79,24.32,None,NaN,12.0,More than 4 hours/week,NaN,Between 1 - 2 hours/week,0,NaN,1,1,0,0.0,NaN,NaN,1.5,0.0
3,66,31.41,More than 10 servings/week,3 cups - 5 cups,12.0,2 - 3 hours/week,NaN,3 - 4 hours/week,0,NaN,1,1,0,0.0,Yes,More than 20 cigarettes a day,3.6,2.0
4,61,29.41,1-2 servings/week,3 cups - 5 cups,3.0,2 - 3 hours/week,NaN,2 - 3 hours/week,1,No,1,1,0,0.0,Yes,More than 20 cigarettes a day,1.6,30.0

In [216]:
df.drop(['Currently Smoking','No of Cigarettes'],axis=1)

,Age,BMI,Diet Servings,Number of Servings,Mod Activity,Mod_Hours,Vig Activity,Vig Hours,Colonoscopy,Polyp,Meds_one,Meds_Two,Family History,Family Numbers,Result,Years Smoking
0,72,29.240,None,NaN,1.0,Up to 1 hour/week,NaN,3 - 4 hours/week,0,NaN,1,1,0,0.0,2.3,19.0
1,58,29.750,3-4 servings/week,More than 5 cups,5.0,2 - 3 hours/week,NaN,3 - 4 hours/week,0,NaN,0,0,1,1.0,7.4,36.0
2,79,24.320,None,NaN,12.0,More than 4 hours/week,NaN,Between 1 - 2 hours/week,0,NaN,1,1,0,0.0,1.5,0.0
3,66,31.410,More than 10 servings/week,3 cups - 5 cups,12.0,2 - 3 hours/week,NaN,3 - 4 hours/week,0,NaN,1,1,0,0.0,3.6,2.0
4,61,29.410,1-2 servings/week,3 cups - 5 cups,3.0,2 - 3 hours/week,NaN,2 - 3 hours/week,1,No,1,1,0,0.0,1.6,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7945,60,27.501,5-6 servings/week,1½ cups - 3 cups,11.0,Between 1 - 2 hours/week,NaN,More than 4 hours/week,1,Yes,1,1,0,0.0,1.8,0.0
7946,50,25.622,1-2 servings/week,½ cup or less,1.0,2 - 3 hours/week,NaN,3 - 4 hours/week,0,NaN,0,0,0,0.0,5.6,0.0
7947,49,22.020,5-6 servings/week,½ cup or less,11.0,Between 1 - 2 hours/week,0.0,NaN,0,NaN,0,1,1,1.0,5.7,0.0
7949,47,19.871,None,NaN,6.0,More than 4 hours/week,0.0,NaN,0,NaN,0,0,1,2.0,11.6,18.0
7950,48,32.178,5-6 servings/week,3 cups - 5 cups,6.0,Up to 1 hour/week,NaN,Between 1 - 2 hours/week,0,NaN,1,0,0,0.0,4.4,47.0

In [217]:
df.drop(['Vig Activity','Vig Hours','Currently Smoking','No of Cigarettes'],axis=1,inplace=True)

C:\Users\Bozo\AppData\Local\Temp\ipykernel_65940\853101917.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['Vig Activity','Vig Hours','Currently Smoking','No of Cigarettes'],axis=1,inplace=True)

In [218]:
df_clean = df.copy()

In [219]:
df_clean.head()

,Age,BMI,Diet Servings,Number of Servings,Mod Activity,Mod_Hours,Colonoscopy,Polyp,Meds_one,Meds_Two,Family History,Family Numbers,Result,Years Smoking
0,72,29.24,None,NaN,1.0,Up to 1 hour/week,0,NaN,1,1,0,0.0,2.3,19.0
1,58,29.75,3-4 servings/week,More than 5 cups,5.0,2 - 3 hours/week,0,NaN,0,0,1,1.0,7.4,36.0
2,79,24.32,None,NaN,12.0,More than 4 hours/week,0,NaN,1,1,0,0.0,1.5,0.0
3,66,31.41,More than 10 servings/week,3 cups - 5 cups,12.0,2 - 3 hours/week,0,NaN,1,1,0,0.0,3.6,2.0
4,61,29.41,1-2 servings/week,3 cups - 5 cups,3.0,2 - 3 hours/week,1,No,1,1,0,0.0,1.6,30.0

In [220]:
diet_servings_map = {
    'None': 0,
    'Less than 1 serving/week': 1,
    '1-2 servings/week': 2,
    '3-4 servings/week': 3,
    '5-6 servings/week': 4,
    '7-10 servings/week': 5,
    'More than 10 servings/week': 6
}

num_servings_map = {
    '½ cup or less': 1,
    'Between ½ cup - 1½ cups': 2,
    '1½ cups - 3 cups': 3,
    '3 cups - 5 cups': 4,
    'More than 5 cups': 5
}
mod_hours = {'Up to 1 hour/week':0,
                'Between 1 - 2 hours/week':1,
                '2 - 3 hours/week':2,
                '3 - 4 hours/week':3,
                'More than 4 hours/week':4}

In [221]:
df_clean['Diet Servings'] = df_clean['Diet Servings'].map(diet_servings_map)

In [222]:
df_clean['Number of Servings'] = df_clean['Number of Servings'].map(num_servings_map)

In [223]:
df_clean['Mod_Hours'] = df_clean['Mod_Hours'].map(mod_hours)

In [224]:
df_clean['Number of Servings'] = df_clean['Number of Servings'].fillna(0)

In [225]:
df_clean.head()

,Age,BMI,Diet Servings,Number of Servings,Mod Activity,Mod_Hours,Colonoscopy,Polyp,Meds_one,Meds_Two,Family History,Family Numbers,Result,Years Smoking
0,72,29.24,0,0.0,1.0,0.0,0,NaN,1,1,0,0.0,2.3,19.0
1,58,29.75,3,5.0,5.0,2.0,0,NaN,0,0,1,1.0,7.4,36.0
2,79,24.32,0,0.0,12.0,4.0,0,NaN,1,1,0,0.0,1.5,0.0
3,66,31.41,6,4.0,12.0,2.0,0,NaN,1,1,0,0.0,3.6,2.0
4,61,29.41,2,4.0,3.0,2.0,1,No,1,1,0,0.0,1.6,30.0

In [226]:
#creating the Colonoscopy / Polyp interaction
df_clean['Polyp'] = df_clean['Polyp'].map({'Yes': 1, 'No': 0})

In [227]:
df_clean['Polyp'] = df_clean['Polyp'].fillna(-1)

In [228]:
df_clean['Colonoscopy_Polyps_Interaction'] = df_clean['Colonoscopy'] * df_clean['Polyp']

In [229]:
df_clean.head()

,Age,BMI,Diet Servings,Number of Servings,Mod Activity,Mod_Hours,Colonoscopy,Polyp,Meds_one,Meds_Two,Family History,Family Numbers,Result,Years Smoking,Colonoscopy_Polyps_Interaction
0,72,29.24,0,0.0,1.0,0.0,0,-1.0,1,1,0,0.0,2.3,19.0,-0.0
1,58,29.75,3,5.0,5.0,2.0,0,-1.0,0,0,1,1.0,7.4,36.0,-0.0
2,79,24.32,0,0.0,12.0,4.0,0,-1.0,1,1,0,0.0,1.5,0.0,-0.0
3,66,31.41,6,4.0,12.0,2.0,0,-1.0,1,1,0,0.0,3.6,2.0,-0.0
4,61,29.41,2,4.0,3.0,2.0,1,0.0,1,1,0,0.0,1.6,30.0,0.0

In [230]:
df_clean.drop(['Colonoscopy','Polyp'],axis=1,inplace=True)

In [232]:
df_clean.head()

,Age,BMI,Diet Servings,Number of Servings,Mod Activity,Mod_Hours,Meds_one,Meds_Two,Family History,Family Numbers,Result,Years Smoking,Colonoscopy_Polyps_Interaction
0,72,29.24,0,0.0,1.0,0.0,1,1,0,0.0,2.3,19.0,-0.0
1,58,29.75,3,5.0,5.0,2.0,0,0,1,1.0,7.4,36.0,-0.0
2,79,24.32,0,0.0,12.0,4.0,1,1,0,0.0,1.5,0.0,-0.0
3,66,31.41,6,4.0,12.0,2.0,1,1,0,0.0,3.6,2.0,-0.0
4,61,29.41,2,4.0,3.0,2.0,1,1,0,0.0,1.6,30.0,0.0

In [233]:
df_clean.drop(['Meds_one','Meds_Two','Family History'],axis=1,inplace=True)

In [234]:
df_clean.to_csv('Cancer Preprocessed February Part Deux.csv', index=False)

In [235]:
df_clean.shape

(784, 10)